
language: python
python:
  - 3.3
  - 3.4

install:
  - pip install aiohttp
  - pip install flake8
  - pip install coverage

script:
  - flake8 aiothrottle tests
  - coverage run --source=aiothrottle setup.py test
  - python setup.py check -rm
