
language: python
python:
  - 3.4.2
  - 3.5

install:
  - pip install aiohttp
  - pip install flake8
  - pip install coveralls

script:
  - flake8 aiothrottle examples tests
  - coverage run --source=aiothrottle setup.py test
  - python setup.py check -rm

after_success:
  - coveralls